### ISSUE TITLE
update request

### ISSUE THREAD

**Issue by lishoujun** [mybatis/ehcache-cache#37] opened 2016-07-22 05:42 UTC
new ehcache version : 
// https://mvnrepository.com/artifact/net.sf.ehcache/ehcache-core
compile group: 'net.sf.ehcache', name: 'ehcache-core', version: '2.6.11'

**Comment by hazendaz** [comment] 2016-07-22 12:31
Not sure i understand the ask.  We are on that echache core currently.  Are you wanting us to officially release an update?

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Jul 22, 2016 at 1:43 AM -0400, "lishoujun" <notifications@github.com<mailto:notifications@github.com>> wrote:


new ehcache version :
// https://mvnrepository.com/artifact/net.sf.ehcache/ehcache-core
compile group: 'net.sf.ehcache', name: 'ehcache-core', version: '2.6.11'

-

**Comment by p0mp0k0** [comment] 2016-07-25 04:51
Does this version support ehcache 3.1?

**Comment by hazendaz** [comment] 2016-07-29 01:16
@p0mp0k0 I re-labeled this to add support for EhCache 3.1.  I have not confirmed other than 3.1 from my understanding is based off jcache so in that regarde I don't think we otherwise currently support it.  If you think it might, please raise a pull request.

**Comment by lishoujun** [comment] 2016-08-02 08:16
@hazendaz 
I use "compile ('org.mybatis.caches:mybatis-ehcache:1.0.3')" in my build.gradle.

![_005](https://cloud.githubusercontent.com/assets/8399413/17321655/4c6a4196-58cc-11e6-81e7-aa7047368387.png)

yes,I want you officially release an update

**Comment by hazendaz** [comment] 2016-08-05 00:30
OK - You got it.  I had made indications back in November about releasing new version of this but was waiting on others to provide more info on issues.  Since that never happened I see no reason not to release this.  I'll do so shortly and will close this once the release is completed.

**Comment by hazendaz** [comment] 2016-08-05 00:33
Actually hang tight a bit.  This is relying on our next parent release.  That release in turn is relying on clirr-maven-plugin release which is expected this coming weekend as our site is broken otherwise.  As soon as we get the parent released, I'll spin back here.  Thanks for your patience in advance.

**Comment by lishoujun** [comment] 2016-08-05 09:47
get it

**Comment by hazendaz** [comment] 2016-11-28 02:16
I'm pushing release now for latest ehcache 2.6.11 support.  Closing ticket.

**Closed by hazendaz** 2016-11-28 02:16 UTC

**Comment by lishoujun** [comment] 2016-11-29 01:23
thanks for your nice work!

**Comment by hazendaz** [comment] 2016-11-29 01:25
Sure no problem!  Sorry it took so long.  It took a while to get the clirr plugin thing I was waiting on then I messed up my local environment but I'm all back in action now.  From now on these will come a bit more frequent :)

**Comment by lishoujun** [comment] 2016-12-15 13:27
Do you mean http://clirr.sourceforge.net/ ?

**Comment by hazendaz** [comment] 2016-12-15 14:10
clirr-maven-plugin.  It was causing issues on our site build with java 8.  I had submitted the patch to maven and it just took time to get it released and then applied on mybatis side.  It's indirectly used here as part of the mybatis parent.
